package com.lockerroom.resourceservice.exceptions;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    // AUTH
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "AUTH_INVALID_CREDENTIALS"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "AUTH_ACCESS_DENIED"),
    TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "AUTH_TOKEN_EXPIRED"),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "AUTH_TOKEN_INVALID"),

    // USER
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_NOT_FOUND"),
    DUPLICATE_USER(HttpStatus.CONFLICT, "USER_EMAIL_DUPLICATED"),
    INVALID_PASSWORD(HttpStatus.BAD_REQUEST, "USER_INVALID_PASSWORD"),
    USER_DISABLED(HttpStatus.FORBIDDEN, "USER_SUSPENDED"),
    DUPLICATE_NICKNAME(HttpStatus.CONFLICT, "USER_NICKNAME_DUPLICATED"),
    USER_PROFILE_ALREADY_COMPLETE(HttpStatus.CONFLICT, "USER_PROFILE_ALREADY_COMPLETE"),

    // POST
    POST_NOT_FOUND(HttpStatus.NOT_FOUND, "POST_NOT_FOUND"),
    POST_ACCESS_DENIED(HttpStatus.FORBIDDEN, "POST_ACCESS_DENIED"),
    POST_ALREADY_REPORTED(HttpStatus.CONFLICT, "POST_ALREADY_REPORTED"),

    // COMMENT
    COMMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "COMMENT_NOT_FOUND"),
    COMMENT_ACCESS_DENIED(HttpStatus.FORBIDDEN, "COMMENT_ACCESS_DENIED"),
    COMMENT_DEPTH_EXCEEDED(HttpStatus.BAD_REQUEST, "COMMENT_REPLY_DEPTH_EXCEEDED"),

    // BOARD
    BOARD_NOT_FOUND(HttpStatus.NOT_FOUND, "BOARD_NOT_FOUND"),
    BOARD_ACCESS_DENIED(HttpStatus.FORBIDDEN, "BOARD_ACCESS_DENIED"),

    // NOTICE
    NOTICE_NOT_FOUND(HttpStatus.NOT_FOUND, "NOTICE_NOT_FOUND"),

    // INQUIRY
    INQUIRY_NOT_FOUND(HttpStatus.NOT_FOUND, "INQUIRY_NOT_FOUND"),
    INQUIRY_ACCESS_DENIED(HttpStatus.FORBIDDEN, "INQUIRY_ACCESS_DENIED"),

    // REQUEST
    REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "REQUEST_NOT_FOUND"),
    REQUEST_ACCESS_DENIED(HttpStatus.FORBIDDEN, "REQUEST_ACCESS_DENIED"),

    // NOTIFICATION
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "NOTIFICATION_NOT_FOUND"),

    // REPORT
    REPORT_NOT_FOUND(HttpStatus.NOT_FOUND, "REPORT_NOT_FOUND"),

    // SPORT
    SPORT_NOT_FOUND(HttpStatus.NOT_FOUND, "SPORT_NOT_FOUND"),

    // FILE
    FILE_NOT_FOUND(HttpStatus.NOT_FOUND, "FILE_NOT_FOUND"),
    FILE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE_UPLOAD_FAILED"),
    FILE_SIZE_EXCEEDED(HttpStatus.BAD_REQUEST, "FILE_SIZE_EXCEEDED"),
    FILE_TYPE_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "FILE_TYPE_NOT_ALLOWED"),
    FILE_COUNT_EXCEEDED(HttpStatus.BAD_REQUEST, "FILE_COUNT_EXCEEDED"),

    // COMMON
    BAD_REQUEST(HttpStatus.BAD_REQUEST, "COMMON_BAD_REQUEST"),
    INVALID_INPUT(HttpStatus.BAD_REQUEST, "COMMON_INVALID_PARAMETER"),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "COMMON_NOT_FOUND"),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "COMMON_INTERNAL_ERROR"),
    IDEMPOTENCY_KEY_MISSING(HttpStatus.BAD_REQUEST, "COMMON_IDEMPOTENCY_KEY_MISSING"),
    IDEMPOTENCY_DUPLICATE(HttpStatus.CONFLICT, "COMMON_DUPLICATE_REQUEST"),
    RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "COMMON_RATE_LIMIT_EXCEEDED");

    private final HttpStatus httpStatus;
    private final String code;

}
